<div class="slider-active owl-carousel pos-absolute">
    <img src="{{ asset('assets/photos/sliders/slider1.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/happy-birthday.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/birthday-cake.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/porsche.png') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/porsche1.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2013-porsche-911-cabriole-20.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/18.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/6206629062acc845f3b2dd5624f5e1d3.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/jaguar-car-wallpaper-For-Desktop-Wallpaper.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/new-porsche-911-carrera-4-carrera-4s-awd-models-48698_1.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/porsche-car-images-hd-best-of-13-best-porsche-carrera-4s-targa-images-on-pinterest-of-porsche-car-images-hd.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/wallpaper2you_214493.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/wallpaper2you_56167.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-05-07_846.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-06-11_850.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-06-20_859.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-06-21_860.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-06-22_861.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-07-02_871.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-07-03_872.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-07-05_874.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-07-24_893.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-07-25_894.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-07-26_895.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-07-27_896.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-07-28_897.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-07-31_900.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-08-09_909.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-08-22_922.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-08-27_927.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-08-31_931.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-09-25_956.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-09-26_957.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-10-05_966.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-10-10_971.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-10-13_974.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/2018-10-14_975.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/AsiaticElephant_EN-IN14096716327_1920x1080.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/bg.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/bg2.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/binaca.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/blue-boat-house-2676184_960_720.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/DolomitesBikeRace_EN-IN10922620742_1920x1080.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/FishingWarehouses_EN-IN11622673825_1920x1080.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/hill-river.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/img.png') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/loung.jpg') }}" alt="Slider">
    <img src="{{ asset('assets/photos/sliders/mauritius-beache.jpg') }}" alt="Slider">
</div>
